// @title Pocket RPG Kit — The Sunstone of Bramble Hollow
// examples/sunstone/sunstone.tsx — the complete three-map sample game with
// attract mode. After 10 seconds without input it replays the frozen
// 539-frame winning playthrough (demo-tape.ts, generated by journey.ts);
// any button takes over on that frame, L rewinds 3 virtual seconds, and
// SELECT hands the session back to the demo. On a host with data.fs, an
// attract-tape.json at the app data root replaces the built-in tape.
import { mount } from "@pocketjs/framework";
// In an app that depends on the published package these are
// "pocket-rpgkit/ui" / "pocket-rpgkit/host"; the in-repo example imports
// the sources relatively so the PocketJS pass-1 transform walks them.
import { GameView } from "../../src/ui/GameView.tsx";
import { loadAttractTape } from "../../src/host/attract-tape.ts";
import { buildGame } from "./game-data.ts";
import { GAME_ASSETS } from "./assets-game.ts";
import { DEMO_TAPE_RUNS } from "./demo-tape.ts";

mount(() => (
  <GameView
    project={buildGame().project}
    assets={GAME_ASSETS}
    attractTape={loadAttractTape(DEMO_TAPE_RUNS).masks}
  />
));
