// AUTO-GENERATED by examples/meadow/gen-assets.ts — minimal example asset
// literals and walker frame tables. Do not edit; the PlayerSprite
// component reads the frame tables, the app reads the two baked map
// canvases.

export const MEADOW_GROUND = "assets/meadow-ground.png";
export const MEADOW_UPPER = "assets/meadow-upper.png";
export const WORLD = { w: 320, h: 192 } as const;

export const PLAYER_IDLE: readonly [string, string, string, string] = [
  "assets/player-dir0.png",
  "assets/player-dir1.png",
  "assets/player-dir2.png",
  "assets/player-dir3.png",
];

export const PLAYER_WALK_L: readonly [string, string, string, string] = [
  "assets/player-pose0-l.png",
  "assets/player-pose1-l.png",
  "assets/player-pose2-l.png",
  "assets/player-pose3-l.png",
];

export const PLAYER_WALK_R: readonly [string, string, string, string] = [
  "assets/player-pose0-r.png",
  "assets/player-pose1-r.png",
  "assets/player-pose2-r.png",
  "assets/player-pose3-r.png",
];
