// examples/meadow/gen-assets.ts — bake the minimal example's art.
//
//   bun examples/meadow/gen-assets.ts   (or `bun run gen-assets` for all)
//
// Inputs (assets/src, see ATTRIBUTION.md):
//   town-tiles.png  Kenney Tiny Town, CC0, 12x11 grid of 16px cells
//   hero-*.png      Lanea Zimmerman (Sharm) Tiny 16, CC-BY 3.0, four 4x1
//                   walker atlases
// Outputs (assets/, referenced by full literal in assets-manifest.ts so
// the pak pass bakes them):
//   meadow-ground.png / meadow-upper.png  512x512 PSM_4444 canvases
//   player-dir0..3.png, player-pose{0..3}-{l,r}.png  12 walker frames
//
// The generic pipeline lives in tools/lib/bake.ts; this file only states
// the example's project and file names.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { bakeMap, loadTileCells, loadWalker } from "../../tools/lib/bake.ts";
import { SHEET, buildMiniProject } from "./mini-project.ts";

const EXAMPLE = new URL(".", import.meta.url).pathname; // examples/meadow/
const SRC = join(EXAMPLE, "assets", "src");
const OUT = join(EXAMPLE, "assets");
mkdirSync(OUT, { recursive: true });

const project = buildMiniProject();
const map = project.maps[0]!;
const cells = new Map([[SHEET.id, await loadTileCells(join(SRC, "town-tiles.png"), SHEET.cols, SHEET.rows)]]);

// Pad with the sheet's grass cell (town.0), like the village cooker: the
// world frame clips to the map rect, so canvas pixels past it never show.
const grass = cells.get(SHEET.id)!.cell(0);
const baked = bakeMap(map, cells, { canvasPx: 512, pad: [grass[0]!, grass[1]!, grass[2]!, grass[3]!] });
writeFileSync(join(OUT, "meadow-ground.png"), baked.ground);
writeFileSync(join(OUT, "meadow-upper.png"), baked.upper);

const HERO = ["down", "left", "up", "right"];
const walker = await loadWalker(HERO.map((d) => join(SRC, `hero-${d}.png`)));
const writeFrames = (buffers: Buffer[], kind: "" | "l" | "r"): string[] => {
  const names: string[] = [];
  for (const [facing, buf] of buffers.entries()) {
    const suffix = kind === "" ? `dir${facing}` : `pose${facing}-${kind}`;
    const name = `assets/player-${suffix}.png`;
    writeFileSync(join(OUT, `player-${suffix}.png`), buf);
    names.push(name);
  }
  return names;
};
const idle = writeFrames(walker.idle, "");
const walkL = writeFrames(walker.walkL, "l");
const walkR = writeFrames(walker.walkR, "r");

// images.json marks the baked canvases PSM_4444 (D214). Walker frames are
// plain IMG entries and need no entry.
writeFileSync(
  join(EXAMPLE, "images.json"),
  JSON.stringify(
    {
      "assets/meadow-ground.png": { psm: 2 },
      "assets/meadow-upper.png": { psm: 2 },
    },
    null,
    2,
  ) + "\n",
);

// Runtime manifest: full string literals so pass 1 bakes the names.
const literalList = (names: readonly string[]): string => names.map((n) => `  ${JSON.stringify(n)},`).join("\n");
writeFileSync(
  join(EXAMPLE, "assets-manifest.ts"),
  `// AUTO-GENERATED by examples/meadow/gen-assets.ts — minimal example asset\n` +
    `// literals and walker frame tables. Do not edit; the PlayerSprite\n` +
    `// component reads the frame tables, the app reads the two baked map\n` +
    `// canvases.\n\n` +
    `export const MEADOW_GROUND = "assets/meadow-ground.png";\n` +
    `export const MEADOW_UPPER = "assets/meadow-upper.png";\n` +
    `export const WORLD = { w: ${baked.widthPx}, h: ${baked.heightPx} } as const;\n\n` +
    `export const PLAYER_IDLE: readonly [string, string, string, string] = [\n${literalList(idle)}\n];\n\n` +
    `export const PLAYER_WALK_L: readonly [string, string, string, string] = [\n${literalList(walkL)}\n];\n\n` +
    `export const PLAYER_WALK_R: readonly [string, string, string, string] = [\n${literalList(walkR)}\n];\n`,
);

console.log(
  `pocket-rpgkit gen-assets: map ${map.id} ${map.width}x${map.height} (${baked.widthPx}x${baked.heightPx}), ` +
    `2 canvases 512px PSM_4444, 12 walker frames`,
);
